/* Generated By:JavaCC: Do not edit this line. Emoji_LanguageTreeConstants.java Version 5.0 */
package CPCS302_Project_jjt;

public interface Emoji_LanguageTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTMTS = 1;
  public int JJTDECLERATION_STMT = 2;
  public int JJTCONSTANT_STMT = 3;
  public int JJTASSIGNMENT_STMT = 4;
  public int JJTSTMT = 5;
  public int JJTARITHMETIC_STMT = 6;
  public int JJTRELATIONAL_STMT = 7;
  public int JJTBOOLEAN_STMT = 8;
  public int JJTARITHMETIC_OPERATION = 9;
  public int JJTRELATIONAL_OPERATION = 10;
  public int JJTLOGICAL_OPERATORS = 11;
  public int JJTARRAY = 12;
  public int JJTLIST = 13;
  public int JJTITERATIVE_STMT = 14;
  public int JJTCONDITIONAL_STMT = 15;
  public int JJTCONDITION = 16;
  public int JJTELSE_STMT = 17;
  public int JJTSTRING = 18;
  public int JJTOPERAND = 19;
  public int JJTNUMBER = 20;
  public int JJTPLUS = 21;
  public int JJTMINUS = 22;
  public int JJTMULTIPLY = 23;
  public int JJTDIVIDE = 24;
  public int JJTREMAINDER = 25;
  public int JJTPOWER = 26;
  public int JJTASSIGNMENT = 27;
  public int JJTIS_EQUAL = 28;
  public int JJTNOT_EQUAL = 29;
  public int JJTGREATER_THAN = 30;
  public int JJTGREATER_THAN_OR_EQUAL = 31;
  public int JJTLESS_THAN = 32;
  public int JJTLESS_THAN_OR_EQUAL = 33;
  public int JJTAND = 34;
  public int JJTOR = 35;
  public int JJTNOT = 36;
  public int JJTOPEN_ROUND_BRACKET = 37;
  public int JJTCLOSE_ROUND_BRACKET = 38;
  public int JJTOPEN_SQUARE_BRACKET = 39;
  public int JJTCLOSE_SQUARE_BRACKET = 40;
  public int JJTOPEN_ANGLE_BRACKET = 41;
  public int JJTCLOSE_ANGLE_BRACKET = 42;
  public int JJTEND_STATEMENT = 43;
  public int JJTBAR = 44;
  public int JJTLETTER = 45;
  public int JJTSYMBOL = 46;
  public int JJTID = 47;
  public int JJTIN = 48;
  public int JJTFL = 49;
  public int JJTBO = 50;
  public int JJTCONSTANT = 51;
  public int JJTINCASE = 52;
  public int JJTSO = 53;
  public int JJTELSE = 54;
  public int JJTEND = 55;
  public int JJTREPEAT = 56;
  public int JJTARR = 57;


  public String[] jjtNodeName = {
    "Start",
    "Stmts",
    "Decleration_Stmt",
    "Constant_Stmt",
    "Assignment_Stmt",
    "Stmt",
    "Arithmetic_Stmt",
    "Relational_Stmt",
    "Boolean_Stmt",
    "Arithmetic_Operation",
    "Relational_Operation",
    "Logical_Operators",
    "Array",
    "List",
    "Iterative_Stmt",
    "Conditional_Stmt",
    "Condition",
    "Else_Stmt",
    "String",
    "Operand",
    "Number",
    "PLUS",
    "MINUS",
    "MULTIPLY",
    "DIVIDE",
    "REMAINDER",
    "POWER",
    "ASSIGNMENT",
    "IS_EQUAL",
    "NOT_EQUAL",
    "GREATER_THAN",
    "GREATER_THAN_OR_EQUAL",
    "LESS_THAN",
    "LESS_THAN_OR_EQUAL",
    "AND",
    "OR",
    "NOT",
    "OPEN_ROUND_BRACKET",
    "CLOSE_ROUND_BRACKET",
    "OPEN_SQUARE_BRACKET",
    "CLOSE_SQUARE_BRACKET",
    "OPEN_ANGLE_BRACKET",
    "CLOSE_ANGLE_BRACKET",
    "END_STATEMENT",
    "BAR",
    "LETTER",
    "SYMBOL",
    "ID",
    "IN",
    "FL",
    "BO",
    "CONSTANT",
    "INCASE",
    "SO",
    "ELSE",
    "END",
    "REPEAT",
    "ARR",
  };
}
/* JavaCC - OriginalChecksum=53100c24d1dad578ad772b6381feb35b (do not edit this line) */
